module.exports = [
    { "id": 1, "author": "MF DOOM", "text": "I’ll put whatever up there for the visible eye." },
    { "id": 2, "author": "MF DOOM", "text": "I’m doing the shows. The stage is my canvas." },
    { "id": 3, "author": "MF DOOM", "text": "Just remember all caps when you spell the man’s name." },
    { "id": 4, "author": "MF DOOM", "text": "The mask is a slight theme for people to enjoy, and it adds mystery." },
    { "id": 5, "author": "MF DOOM", "text": "I spent 35 years growing up in the U.S., and it had its ups and downs." },
    { "id": 6, "author": "MF DOOM", "text": "The ‘Doom’ thing is to be able to come at things with a different point of view." },
    { "id": 7, "author": "MF DOOM", "text": "Ever since third grade, I had a notebook and was putting together words just for fun." },
    { "id": 8, "author": "MF DOOM", "text": "And since when the rap game had to do with killin’ a cat, what type o’ chitlins is that?" },
    { "id": 9, "author": "MF DOOM", "text": "You could either ignore this advice, or take it from me, be too nice, and people take you for a dummy." },
    { "id": 10, "author": "MF DOOM", "text": "I decided the mask would just add to the mystique of the character as well as make Doom stand out." },
    { "id": 11, "author": "MF DOOM", "text": "I’m incognito. It’s all-new, all fun." },
    { "id": 12, "author": "MF DOOM", "text": "I can’t perform without the mask or be seen without it on stage, or else it’ll distract from the whole persona." },
    { "id": 13, "author": "MF DOOM", "text": "Only in America could you find a way to make a healthy buck, and still keep your attitude on self-destruct." },
    { "id": 14, "author": "MF DOOM", "text": "I liked being able to speak to somebody and throw it back and forth, and they can’t predict what you’re going to say next." },
    { "id": 15, "author": "MF DOOM", "text": "I liked different etymologies, different slang that came out in different eras. Different languages. Different dialects." },
    { "id": 16, "author": "MF DOOM", "text": "I have no friends here apart from the dudes at my record label, and I didn’t go to school with no one. Nobody knows me." },
    { "id": 17, "author": "MF DOOM", "text": "I think – a lot of times in hip-hop, especially – artists get kind of pigeonholed into being ‘the guy,’ and it’s kind of limiting in a way." },
    { "id": 18, "author": "MF DOOM", "text": "I thought it’d be an easy way for people to see and differentiate between characters, sorta like when an actor gains weight for a role." },
    { "id": 19, "author": "MF DOOM", "text": "I’m always trying to show versatility. I’m juggling, and I’m flipping fire, and I’m chewing gum and rhyming at the same time… on a unicycle while playing the drums." },
    { "id": 20, "author": "MF DOOM", "text": "Being older now, grown, I’m like, ‘What do we really do that’s fun?’" },
    { "id": 21, "author": "MF DOOM", "text": "I’m not trying to be the next Tupac, but I don’t know how long I’m going to be on this planet. So while I’m here, let me make something that’s timeless." },
    { "id": 22, "author": "MF DOOM", "text": "I make hip-hop, but use Doom as a character to convey stories that a normal dude can’t." },
    { "id": 23, "author": "MF DOOM", "text": "The idea of having different characters is really just to get the storyline across, you know?" },
    { "id": 24, "author": "MF DOOM", "text": "You have writers that write about crazy characters, but that doesn’t mean the writer himself is crazy." },
    { "id": 25, "author": "MF DOOM", "text": "We all tend to be in the same circles – people like my Wu-Tang brothers, or Black Thought from The Roots." },
    { "id": 26, "author": "MF DOOM", "text": "I’m kind of corny when you think about it. What could I rhyme about? Let me see, um, I gotta pay the rent today." },
    { "id": 27, "author": "MF DOOM", "text": "Everybody nowadays rhymes, but out of the people that really, really do it well, it’s still a small community of artists." },
    { "id": 28, "author": "MF DOOM", "text": "But I’m down with all of it. Chuck D or Danny Brown? I feel comfortable with all of them. Word up, kid! Word up, man!" },
    { "id": 29, "author": "MF DOOM", "text": "I get that mainly from novels and that style of writing or movies where there’s multiple characters who carry the storyline." },
    { "id": 30, "author": "MF DOOM", "text": "Nowadays, you can just do it – have your name-brand clothes, do songs with rock n’ rollers – and it’s not considered selling out." },
    { "id": 31, "author": "MF DOOM", "text": "Prince Paul is another good friend; he’s like an older brother. He’ll criticize and be brutally honest with you. That’s what I like about Paul." },
    { "id": 32, "author": "MF DOOM", "text": "When I listen to hip-hop, I listen to Just Ice, Boogie Down Productions, Ultramagnetic MCs. I grew up in that age, and it was memorable." },
    { "id": 33, "author": "MF DOOM", "text": "Doom is a classic supervillain, akin to the Phantom of the Opera. It’s not about revenge so much as, like, ‘I’m back – now watch this!’ It all boils down to the music." },
    { "id": 34, "author": "MF DOOM", "text": "Hip-hop is so saturated with the same old same old that people always expect the guy to actually be the guy. They want you to be real and straight from the streets and all that." },
    { "id": 35, "author": "MF DOOM", "text": "The song ‘Bite the Thong’ in particular, with Damon Albarn, really encapsulates the whole dilemma of, ‘Hmm, should I stay on the underground when everybody else is selling out?" },
    { "id": 36, "author": "MF DOOM", "text": "Got more soul than a sock with a hole." },
    { "id": 37, "author": "MF DOOM", "text": "Living on borrowed time, the clock ticks faster." },
    { "id": 38, "author": "MF DOOM", "text": "After rocking parties they depart in a jalopy, watch the drop top poppy." },
    { "id": 39, "author": "MF DOOM", "text": "A visual always brings a first impression. But if there’s going to be a first impression, I might as well use it to control the story. So why not do something like throw a mask on?" },
    { "id": 40, "author": "MF DOOM", "text": "Easy as pi, three point one four, one more one false move and they’re done for." }
];
